services:
  kiki-server:
    build: .
    ports: 
      - "127.0.0.1:5000:5000"
    volumes: 
      - "./:/app"
      - "/etc/localtime:/etc/localtime:ro"
    command: /bin/bash -c "gunicorn -c gunicorn_config.py server:app"
